global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: 'oas'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:5000']  
